//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_ChatRoom
    {
        public int Id { get; set; }
        public int Id_Employee { get; set; }
        public int Id_ChatRoom { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
